version: '3.8'

services:
  mantisbt:
    build: .
    ports:
      - "8989:80"
    environment:
      TZ: Asia/Jakarta
    volumes:
      - ./config/config_inc.php:/var/www/html/config/config_inc.php
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mantis
      MYSQL_USER: mantis
      MYSQL_PASSWORD: mantis
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
